config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'

  get 'password_resets/edit'

  root   'static_pages#home'
  get    '/faq',     to: 'static_pages#faq'
  get    '/carriers',to: 'static_pages#carriers'
  get    '/about',   to: 'static_pages#about'
  get    '/contact', to: 'static_pages#contact'
  get    '/signup',  to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :microposts,          only: [:create, :destroy]
  resources :relationships,       only: [:create, :destroy]
end

app/views/layouts/_footer.erb
<footer class="footer">
  <small>
    Deepwood &copy; <%= Time.now.year%>
  </small>
  <nav>
    <ul>
      <li><%= link_to "Home", root_path %></li>
      <li><%= link_to "FAQ", faq_path %></li>
      <li><%= link_to "We are hiring", carriers_path %></li>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.erb
\<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to(root_path, id: "logo") do %>
      <span class="glyphicon glyphicon-th"/>
    <% end %>
    <%= link_to image_tag("deepwood.png", alt: "Deepwood", id:"deepwood"),
                root_url  %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <% if logged_in? %>
            <li>
              <%= link_to(users_path) do %>
                  <span class="glyphicon glyphicon-list icon"/>
              <% end %>
            </li>
            <li>
              <%= link_to(current_user) do %>
                  <span class="glyphicon glyphicon-user icon"/>
              <% end %>
            </li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
</script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag    'application', media: 'all',
                             'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <%= render 'layouts/shim' %>

</head>
<body>
<% if logged_in? %>
  <%= render 'layouts/header' %>
<% end %>
<div class="container">
  <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %></div>
  <% end %>
  <%= yield %>
  <%= render 'layouts/footer' %>
  <%= debug(params) if Rails.env.development? %>
</div>
</body>
</html>